name: zephyr

permissions: read-all

on:
  push:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: ""
  PREFIX: 0
  SHA: 0

jobs:
  build-in-zephyr-ci-container:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    container: ghcr.io/zephyrproject-rtos/ci:v0.27.4
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains

    strategy:
      matrix:
        board: [nucleo_f411re] # , qemu_cortex_m3]
        application:
          [zephyr/samples/basic/blinky, zephyr/samples/basic/sys_heap]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize workspace
        run: |
          west init
          west update -o=--depth=1 -n
          west zephyr-export

      - name: Build firmware "${{ matrix.application }}" for ${{ matrix.board }}
        run: |
          west build -p always -b ${{ matrix.board }} ${{ matrix.application }}

      - name: Create filename prefix
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          {
            echo "APP_NAME=$(echo ${{ matrix.application }} | sed 's/\//_/g')"
            echo "PREFIX=${{ github.event.repository.name }}-${{ matrix.board }}"
            echo "SHA=$(git rev-parse --short HEAD)"
          } >> "$GITHUB_ENV"

      - name: Prepare artifacts
        run: |
          cd build/zephyr
          mkdir -p artifacts
          mv zephyr.bin ./artifacts/${{ env.PREFIX }}-${{ env.SHA }}.bin
          mv zephyr.elf ./artifacts/${{ env.PREFIX }}-${{ env.SHA }}.elf
          mv zephyr.hex ./artifacts/${{ env.PREFIX }}-${{ env.SHA }}.hex

      - name: Save artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: build_artifacts_${{ github.run_id }}_${{ env.APP_NAME }}_${{ matrix.board }}
          path: |
            build/zephyr/artifacts/*
